routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/',
    function () {
        return view('pages.home');
    }
)->name('home');

Route::get(
    '/webflow',
    function () {
        return view('pages.webflow');
    }
)->name('webflow');

Route::get(
    '/laravel',
    function () {
        return view('pages.laravel');
    }
)->name('laravel');

Route::get(
    '/prestashop',
    function () {
        return view('pages.prestashop');
    }
)->name('prestashop');

Route::get(
    '/contact',
    function () {
        return redirect('/');
    }
);

Route::post('/contact', [ContactController::class, 'send'])->name('contact');

Route::get(
    '/actualites/{slug}',
    [CategoryController::class, 'show']
)->name('category');

Route::get(
    '/actualites/{categorySlug}/{slug}',
    [ArticleController::class, 'show']
)->name('article');

app/Models/Article.php
<?php

namespace App\Models;

use App\Casts\Markdown as CastMarkdown;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Article extends Model
{
    use HasFactory;

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'content' => CastMarkdown::class,
        'published_at' => 'datetime',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getCanBeReadAttribute()
    {
        return $this->is_published && $this->published_at->lte(Carbon::now());
    }

    public function getMetaTitleAttribute()
    {
        return substr($this->title, 0, 52);
    }

    public function getMetaDescriptionAttribute()
    {
        return substr($this->catch_phrase, 0, 150);
    }
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function articles()
    {
        return $this->hasMany(Article::class)
                    ->where('is_published', true)
                    ->where('published_at', '<=', date('Y-m-d'));
    }

    /**
     * @return bool
     */
    protected function getHasArticlesAttribute(): bool
    {
        return $this->articles->isNotEmpty();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\CategoryRepositoryInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryController;

    public function __construct(CategoryRepositoryInterface $categoryController)
    {
        $this->categoryController = $categoryController;
    }

    public function show($slug)
    {
        $category = $this->categoryController->getBySlug($slug);

        return view('category.show', [
            'category' => $category,
        ]);
    }
}

resources/views/category/show.blade.php
@extends('layouts.default')

@section('title')
{{ $category->meta_title }} - UpDaz
@endsection

@section('meta-description')
{{ $category->meta_description }}
@endsection

@section('content')
<div class="relative bg-blue text-white text-center py-16 md:py-20 md:pt-32 md:-mt-24 overflow-hidden min-h-[50vh] md:min-h-0">
    <div class="absolute h-80 bottom-0 lg:left-2/4 lg:-translate-x-1/2 opacity-10">
        @include('elements/illustrations/write-book')
    </div>
    <div class="relative">
        <h1 class="font-title text-4xl lg:text-6xl font-bold">Les articles <span class="text-orange">{{ $category->name }}</span></h1>
        <div class="container mx-auto text-center text-sm mt-6">
            <x-breadcrumb :links="[
                $category->name => route('category', ['slug' => $category->slug])
            ]" />
        </div>
    </div>
</div>

<div class="container mx-auto mt-6">
    <p class="text-center">
        {{ $category->catch_phrase }}
    </p>
</div>

<div class="container px-8 py-12 mx-auto md:px-16 md:py-24">
    @if($category->has_articles)
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 align-top justify-center">
            @foreach( $category->articles->sortByDesc('published_at') as $article)
                @include('elements.article.box')
            @endforeach
        </div>
    @else
        <p class="text-center font-bold">
            Aucune actualité pour le moment
        </p>
        <div class="w-full md:w-1/2 mx-auto">
            @include('elements/illustrations/no-content')
        </div>
    @endif
</div>

@endsection